#!/usr/bin/env python3
"""Build the single-file GUI application for the platform you are standing on.

    uv sync
    uv run python tools/build_exe.py

Produces, in dist/:

    Windows   openm74.exe                     one file, no installer, no admin rights
    macOS     openm74.app  +  the .zip of it  one bundle, nothing to install
    Linux     openm74                         one file

One script rather than one per platform, deliberately: the GUI and the CLI already share a
single code path so the button cannot drift from the terminal, and a second builder is the
same trap one level up -- the platform nobody built this week is the one that quietly stops
producing a working artifact.

Everything the result needs is inside it: Python, Tk, pyserial, and the assembled stages.

Two things to be straight about with anyone who downloads any of these:

  * **They are not signed by a paid identity.** Windows SmartScreen will call it an unknown
    publisher; macOS will refuse it outright on first launch (see below) because it is
    neither signed with a Developer ID nor notarised.  Signing costs money this project
    does not spend.
  * **PyInstaller does not produce reproducible builds**, so rebuilding will NOT give you a
    matching hash.  "Verify my binary by rebuilding it" is not an honest instruction.

Which is why the real answer for anyone who does not want to trust a binary is to build
their own -- the reason the dependency list is one package long is so that this is a
one-minute job rather than a project.  The hash printed at the end goes next to the
download, so at least the file people got is the file that was built.

macOS specifics, because they are not optional knowledge for whoever publishes this:

  * **Gatekeeper will block it on first launch** with "cannot be opened because the
    developer cannot be verified".  That is not a fault in the build.  The user opens it
    once via right-click -> Open (or clears the quarantine flag), and never again.  Say so
    next to the download rather than letting people conclude the file is broken.
  * **The build is for the architecture it was built on** -- this script reports which.
    A universal binary needs a universal Python to build from, which the standard toolchain
    here is not, so an Intel Mac needs its own build on an Intel Mac.
  * The bundle is **ad-hoc signed** by PyInstaller, which is what lets it run at all on
    Apple Silicon.  Ad-hoc is not the same as trusted, and this script verifies only that
    the signature is intact -- it makes no claim about provenance.
"""
import hashlib
import os
import platform
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Not gui.py itself: PyInstaller runs the entry script as a top-level __main__, which
# would leave the package-relative imports inside it with no package to resolve against.
ENTRY = os.path.join(ROOT, "tools", "launch_gui.py")
SRC = os.path.join(ROOT, "src")
STAGES = os.path.join(ROOT, "src", "openm74", "stages")
DIST = os.path.join(ROOT, "dist")
BUILD = os.path.join(ROOT, "build")

IS_WIN = sys.platform == "win32"
IS_MAC = sys.platform == "darwin"
BUNDLE_ID = "io.github.openm74"

# The icon, per platform.  Without one, PyInstaller embeds its own -- so an application
# people are asked to download and trust arrives wearing the packager's logo, which is a
# small thing that reads as an unfinished one.  Generated by tools/make_icon.py; the .icns
# can only be written by macOS, so elsewhere the build falls back to the PNG rather than
# failing, and a checkout on any platform still produces a bundle.
ICONS = os.path.join(SRC, "openm74", "icons")
_ICON = os.path.join(ICONS, "openm74.ico" if sys.platform == "win32"
                     else "openm74.icns" if sys.platform == "darwin" else "openm74.png")
if not os.path.exists(_ICON):
    _ICON = os.path.join(ICONS, "openm74.png")

CMD = [sys.executable, "-m", "PyInstaller",
       "--onefile",                     # one file, run it from anywhere
       "--windowed",                    # no console behind the GUI; on macOS, a real .app
       "--name", "openm74",
       "--paths", SRC,
       "--hidden-import", "openm74.klinebsl",
       "--hidden-import", "serial.tools.list_ports",
       # the assembled stages ride along: the tool checks the bytes it is about to push
       # into an ECU against the assembler's own output before using them
       "--add-data", STAGES + os.pathsep + os.path.join("openm74", "stages"),
       # the icon files ride along too: the window sets its own icon at runtime from the
       # PNG, which is what a Linux window manager and a Windows taskbar actually show
       "--add-data", ICONS + os.pathsep + os.path.join("openm74", "icons"),
       "--distpath", DIST,
       "--workpath", BUILD,
       "--specpath", BUILD,
       "--clean", "--noconfirm"]
if os.path.exists(_ICON):
    CMD += ["--icon", _ICON]
if IS_MAC:
    # Without an identifier the bundle gets one derived from the name, and macOS uses it to
    # key window state and permissions -- worth setting deliberately rather than inheriting.
    CMD += ["--osx-bundle-identifier", BUNDLE_ID]
CMD += [ENTRY]


def artifacts():
    """(the executable to self-test, the thing to publish).

    On macOS those differ: what ships is the .app bundle, but what has to be *run* to
    prove the bundle works is the executable inside it.
    """
    if IS_WIN:
        exe = os.path.join(DIST, "openm74.exe")
        return exe, exe
    if IS_MAC:
        app = os.path.join(DIST, "openm74.app")
        return os.path.join(app, "Contents", "MacOS", "openm74"), app
    exe = os.path.join(DIST, "openm74")
    return exe, exe


def selftest(exe):
    """Run the built file once before calling it built.

    A successful PyInstaller run says nothing about whether the result starts: bundling
    problems -- a missing hidden import, a data file that did not come along, an entry
    script that lost its package -- surface only on first launch.  Without this, "the
    build succeeded" and "the download works" are two different claims and only the first
    one was ever checked.  Ask the executable to reach its own entry point and quit.
    """
    print("\nself-test: does it start?")
    try:
        rc = subprocess.call([exe, "--selftest"], timeout=120)
    except subprocess.TimeoutExpired:
        # A frozen import error in a windowed build puts up a modal dialog and waits, so a
        # hang here is a failure with a specific meaning, not a slow machine.
        sys.exit("the executable did not reach its entry point (stuck -- run it by hand "
                 "to see the dialog it is showing)")
    if rc:
        sys.exit("the executable exited %d on startup; it is broken, not shipped" % rc)
    print("  ok, it starts")


def min_macos(exe):
    """The oldest macOS this build can actually run on, read out of the binary.

    Derived rather than hard-coded: it comes from the toolchain that built the bootloader
    and the interpreter, so a hard-coded number goes stale the first time either moves,
    and a WRONG one is worse than none -- it either turns away machines that would have
    worked or promises machines that will not.
    """
    try:
        out = subprocess.run(["otool", "-l", exe], capture_output=True, text=True).stdout
    except Exception:
        return None
    m = re.search(r"LC_BUILD_VERSION.*?\bminos\s+([0-9]+(?:\.[0-9]+)*)", out, re.S)
    if not m:
        m = re.search(r"LC_VERSION_MIN_MACOSX.*?\bversion\s+([0-9]+(?:\.[0-9]+)*)", out, re.S)
    return m.group(1) if m else None


def declare_min_macos(app, exe):
    """Write the floor into the bundle, then RE-SIGN it.

    Without LSMinimumSystemVersion, an older Mac does not refuse the application politely
    -- it launches it and dies in the dynamic linker, which reads as "this download is
    broken" rather than "this Mac is too old".

    Editing Info.plist invalidates the signature PyInstaller just applied, and on Apple
    Silicon an invalid signature is not a warning: the bundle will not start at all.  So
    the patch and the re-sign are one operation, never two.
    """
    ver = min_macos(exe)
    if not ver:
        print("  WARNING: could not read the minimum macOS out of the binary; "
              "LSMinimumSystemVersion left unset")
        return
    plist = os.path.join(app, "Contents", "Info.plist")
    subprocess.check_call(["/usr/libexec/PlistBuddy", "-c",
                           "Add :LSMinimumSystemVersion string %s" % ver, plist])
    print("  declares macOS %s or newer (read from the built binary)" % ver)
    subprocess.check_call(["codesign", "--force", "--sign", "-", app])
    print("  re-signed after the edit (an edited bundle keeps no signature)")


def check_signature(app):
    """Report what the signature actually is.  Never claim more than that."""
    print("\nsignature:")
    rc = subprocess.call(["codesign", "--verify", "--deep", "--strict", app])
    if rc:
        print("  WARNING: codesign --verify failed (%d) -- the bundle may not launch on "
              "Apple Silicon" % rc)
        return
    out = subprocess.run(["codesign", "-dvv", app], capture_output=True, text=True).stderr
    authority = [l.strip() for l in out.splitlines() if l.startswith("Authority=")]
    print("  intact; %s" % (", ".join(authority) if authority
                            else "ad-hoc (no signing authority) -- expected, see the "
                                 "module docstring"))


def package(app):
    """Zip the bundle the way Apple wants it zipped.

    A .app is a directory, so it cannot be published as one file or hashed as one.  ditto
    preserves the bundle's metadata and its signature; a plain `zip` can break both, and
    the failure shows up as a bundle that will not launch on someone else's machine rather
    than as an error here.
    """
    zpath = os.path.join(DIST, "openm74-macos-%s.zip" % platform.machine())
    if os.path.exists(zpath):
        os.remove(zpath)
    subprocess.check_call(["ditto", "-c", "-k", "--sequesterRsrc", "--keepParent",
                           app, zpath])
    return zpath


def main():
    print("building for %s / %s (python %s, Tk from this interpreter)"
          % (sys.platform, platform.machine(), platform.python_version()))
    print("$ " + " ".join(CMD))
    # Captured as well as shown, so the one failure with a non-obvious fix can be answered
    # with that fix instead of with a guess.  MEASURED on a clean Ubuntu 22.04: the build
    # dies on a missing libpython, and "Installed?  uv sync" -- which was the only advice
    # here -- sends the reader to look at the wrong thing entirely.
    proc = subprocess.Popen(CMD, cwd=ROOT, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, universal_newlines=True)
    out = []
    for line in proc.stdout:
        sys.stdout.write(line)
        out.append(line)
    rc = proc.wait()
    if rc:
        log = "".join(out)
        if "shared library" in log and "libpython" in log:
            v = "%d.%d" % sys.version_info[:2]
            sys.exit("PyInstaller needs Python's SHARED library, which Debian and Ubuntu "
                     "package separately from the interpreter:\n"
                     "    sudo apt install libpython%s\n"
                     "(or libpython3-dev).  Nothing is wrong with your checkout -- this is "
                     "a distribution packaging detail, and it stops a onefile build cold."
                     % v)
        sys.exit("PyInstaller failed (%d).  Installed?  uv sync" % rc)

    exe, shipped = artifacts()
    if not os.path.exists(exe):
        sys.exit("PyInstaller reported success but %s is not there" % exe)
    if IS_MAC:
        print("\nbundle:")
        declare_min_macos(shipped, exe)
    # After the plist edit and the re-sign, never before: what gets tested has to be what
    # gets shipped, and on macOS the bundle is not finished until it is signed again.
    selftest(exe)
    if IS_MAC:
        check_signature(shipped)
        # --onefile --windowed leaves the plain executable next to the bundle as well.
        # It is the same program, but it is not what ships, and two 12 MB artifacts with
        # different hashes in one directory is how the wrong one ends up published.
        loose = os.path.join(DIST, "openm74")
        if os.path.exists(loose):
            os.remove(loose)
            print("  removed the redundant loose binary; the bundle is the artifact")
        shipped = package(shipped)

    data = open(shipped, "rb").read()
    digest = hashlib.sha256(data).hexdigest().upper()
    with open(shipped + ".sha256", "w") as f:
        f.write("%s *%s\n" % (digest, os.path.basename(shipped)))
    print("\nbuilt: %s\n%d bytes\nsha256 %s" % (shipped, len(data), digest))
    print("Hash written next to it; publish both.")
    if IS_MAC:
        print("\nThis is a %s build and runs on %s Macs only.  It is not notarised, so the"
              % (platform.machine(), platform.machine()))
        print("first launch needs right-click -> Open.  Both facts belong next to the")
        print("download, not in a support thread afterwards.")


if __name__ == "__main__":
    main()
